kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    # Add extra port mappings if needed for testing
    extraPortMappings:
      - containerPort: 30000
        hostPort: 30000
        listenAddress: "127.0.0.1"
        protocol: TCP
# Enable feature gates if needed
featureGates:
  "EphemeralContainers": true
# Set resource limits for CI environment
kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        max-pods: "110"
  - |
    kind: KubeletConfiguration
    evictionHard:
      memory.available: "100Mi"
      nodefs.available: "5%"