{{- if not .Values.app.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rust-docs-mcp-server.secretName" . }}
  labels:
    {{- include "rust-docs-mcp-server.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.app.secrets.openaiApiKey }}
  openai-api-key: {{ .Values.app.secrets.openaiApiKey | b64enc | quote }}
  {{- else }}
  openai-api-key: {{ "" | b64enc | quote }}
  {{- end }}

  {{- if .Values.app.secrets.voyageApiKey }}
  voyage-api-key: {{ .Values.app.secrets.voyageApiKey | b64enc | quote }}
  {{- else }}
  voyage-api-key: {{ "" | b64enc | quote }}
  {{- end }}

  {{- if and (not .Values.postgresql.enabled) .Values.app.secrets.databasePassword }}
  database-password: {{ .Values.app.secrets.databasePassword | b64enc | quote }}
  {{- end }}
{{- end }}